/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hughes.billing.voipworkorder.dto.avro.req;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class headers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6929916180991920644L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"headers\",\"namespace\":\"com.hughes.billing.voipworkorder.dto.avro.req\",\"fields\":[{\"name\":\"KEY\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<headers> ENCODER =
      new BinaryMessageEncoder<headers>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<headers> DECODER =
      new BinaryMessageDecoder<headers>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<headers> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<headers> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<headers>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this headers to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a headers from a ByteBuffer. */
  public static headers fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence KEY;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public headers() {}

  /**
   * All-args constructor.
   * @param KEY The new value for KEY
   */
  public headers(java.lang.CharSequence KEY) {
    this.KEY = KEY;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return KEY;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: KEY = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'KEY' field.
   * @return The value of the 'KEY' field.
   */
  public java.lang.CharSequence getKEY() {
    return KEY;
  }

  /**
   * Sets the value of the 'KEY' field.
   * @param value the value to set.
   */
  public void setKEY(java.lang.CharSequence value) {
    this.KEY = value;
  }

  /**
   * Creates a new headers RecordBuilder.
   * @return A new headers RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder newBuilder() {
    return new com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder();
  }

  /**
   * Creates a new headers RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new headers RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder other) {
    return new com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder(other);
  }

  /**
   * Creates a new headers RecordBuilder by copying an existing headers instance.
   * @param other The existing instance to copy.
   * @return A new headers RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.req.headers other) {
    return new com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder(other);
  }

  /**
   * RecordBuilder for headers instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<headers>
    implements org.apache.avro.data.RecordBuilder<headers> {

    private java.lang.CharSequence KEY;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.KEY)) {
        this.KEY = data().deepCopy(fields()[0].schema(), other.KEY);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing headers instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.req.headers other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.KEY)) {
        this.KEY = data().deepCopy(fields()[0].schema(), other.KEY);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'KEY' field.
      * @return The value.
      */
    public java.lang.CharSequence getKEY() {
      return KEY;
    }

    /**
      * Sets the value of the 'KEY' field.
      * @param value The value of 'KEY'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder setKEY(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.KEY = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'KEY' field has been set.
      * @return True if the 'KEY' field has been set, false otherwise.
      */
    public boolean hasKEY() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'KEY' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.req.headers.Builder clearKEY() {
      KEY = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public headers build() {
      try {
        headers record = new headers();
        record.KEY = fieldSetFlags()[0] ? this.KEY : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<headers>
    WRITER$ = (org.apache.avro.io.DatumWriter<headers>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<headers>
    READER$ = (org.apache.avro.io.DatumReader<headers>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
