server:
  port: 8080

pubsub:
  project:
    id: 'playground-s-11-f630ab37'
  topic:
    id: 'testTopic'
  subscription:
    id: 'testSubscription'
  publisher:
    logMessage:
      enabled: ${BILLING_PUBSUB_LOGMESSAGE_ENABLED}