/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hughes.sdg.avro.types;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CreditCardInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6197388081539394474L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreditCardInfo\",\"namespace\":\"com.hughes.sdg.avro.types\",\"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Number\",\"type\":\"string\"},{\"name\":\"ExpirationMonth\",\"type\":\"string\"},{\"name\":\"ExpirationYear\",\"type\":\"string\"},{\"name\":\"CVV\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreditCardInfo> ENCODER =
      new BinaryMessageEncoder<CreditCardInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreditCardInfo> DECODER =
      new BinaryMessageDecoder<CreditCardInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CreditCardInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CreditCardInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreditCardInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CreditCardInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CreditCardInfo from a ByteBuffer. */
  public static CreditCardInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Type;
  @Deprecated public java.lang.CharSequence Number;
  @Deprecated public java.lang.CharSequence ExpirationMonth;
  @Deprecated public java.lang.CharSequence ExpirationYear;
  @Deprecated public java.lang.CharSequence CVV;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreditCardInfo() {}

  /**
   * All-args constructor.
   * @param Type The new value for Type
   * @param Number The new value for Number
   * @param ExpirationMonth The new value for ExpirationMonth
   * @param ExpirationYear The new value for ExpirationYear
   * @param CVV The new value for CVV
   */
  public CreditCardInfo(java.lang.CharSequence Type, java.lang.CharSequence Number, java.lang.CharSequence ExpirationMonth, java.lang.CharSequence ExpirationYear, java.lang.CharSequence CVV) {
    this.Type = Type;
    this.Number = Number;
    this.ExpirationMonth = ExpirationMonth;
    this.ExpirationYear = ExpirationYear;
    this.CVV = CVV;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Type;
    case 1: return Number;
    case 2: return ExpirationMonth;
    case 3: return ExpirationYear;
    case 4: return CVV;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Type = (java.lang.CharSequence)value$; break;
    case 1: Number = (java.lang.CharSequence)value$; break;
    case 2: ExpirationMonth = (java.lang.CharSequence)value$; break;
    case 3: ExpirationYear = (java.lang.CharSequence)value$; break;
    case 4: CVV = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Type' field.
   * @return The value of the 'Type' field.
   */
  public java.lang.CharSequence getType() {
    return Type;
  }

  /**
   * Sets the value of the 'Type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.Type = value;
  }

  /**
   * Gets the value of the 'Number' field.
   * @return The value of the 'Number' field.
   */
  public java.lang.CharSequence getNumber() {
    return Number;
  }

  /**
   * Sets the value of the 'Number' field.
   * @param value the value to set.
   */
  public void setNumber(java.lang.CharSequence value) {
    this.Number = value;
  }

  /**
   * Gets the value of the 'ExpirationMonth' field.
   * @return The value of the 'ExpirationMonth' field.
   */
  public java.lang.CharSequence getExpirationMonth() {
    return ExpirationMonth;
  }

  /**
   * Sets the value of the 'ExpirationMonth' field.
   * @param value the value to set.
   */
  public void setExpirationMonth(java.lang.CharSequence value) {
    this.ExpirationMonth = value;
  }

  /**
   * Gets the value of the 'ExpirationYear' field.
   * @return The value of the 'ExpirationYear' field.
   */
  public java.lang.CharSequence getExpirationYear() {
    return ExpirationYear;
  }

  /**
   * Sets the value of the 'ExpirationYear' field.
   * @param value the value to set.
   */
  public void setExpirationYear(java.lang.CharSequence value) {
    this.ExpirationYear = value;
  }

  /**
   * Gets the value of the 'CVV' field.
   * @return The value of the 'CVV' field.
   */
  public java.lang.CharSequence getCVV() {
    return CVV;
  }

  /**
   * Sets the value of the 'CVV' field.
   * @param value the value to set.
   */
  public void setCVV(java.lang.CharSequence value) {
    this.CVV = value;
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.hughes.sdg.avro.types.CreditCardInfo.Builder newBuilder() {
    return new com.hughes.sdg.avro.types.CreditCardInfo.Builder();
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.hughes.sdg.avro.types.CreditCardInfo.Builder newBuilder(com.hughes.sdg.avro.types.CreditCardInfo.Builder other) {
    return new com.hughes.sdg.avro.types.CreditCardInfo.Builder(other);
  }

  /**
   * Creates a new CreditCardInfo RecordBuilder by copying an existing CreditCardInfo instance.
   * @param other The existing instance to copy.
   * @return A new CreditCardInfo RecordBuilder
   */
  public static com.hughes.sdg.avro.types.CreditCardInfo.Builder newBuilder(com.hughes.sdg.avro.types.CreditCardInfo other) {
    return new com.hughes.sdg.avro.types.CreditCardInfo.Builder(other);
  }

  /**
   * RecordBuilder for CreditCardInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreditCardInfo>
    implements org.apache.avro.data.RecordBuilder<CreditCardInfo> {

    private java.lang.CharSequence Type;
    private java.lang.CharSequence Number;
    private java.lang.CharSequence ExpirationMonth;
    private java.lang.CharSequence ExpirationYear;
    private java.lang.CharSequence CVV;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hughes.sdg.avro.types.CreditCardInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Type)) {
        this.Type = data().deepCopy(fields()[0].schema(), other.Type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Number)) {
        this.Number = data().deepCopy(fields()[1].schema(), other.Number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ExpirationMonth)) {
        this.ExpirationMonth = data().deepCopy(fields()[2].schema(), other.ExpirationMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ExpirationYear)) {
        this.ExpirationYear = data().deepCopy(fields()[3].schema(), other.ExpirationYear);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CVV)) {
        this.CVV = data().deepCopy(fields()[4].schema(), other.CVV);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CreditCardInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hughes.sdg.avro.types.CreditCardInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Type)) {
        this.Type = data().deepCopy(fields()[0].schema(), other.Type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Number)) {
        this.Number = data().deepCopy(fields()[1].schema(), other.Number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ExpirationMonth)) {
        this.ExpirationMonth = data().deepCopy(fields()[2].schema(), other.ExpirationMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ExpirationYear)) {
        this.ExpirationYear = data().deepCopy(fields()[3].schema(), other.ExpirationYear);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CVV)) {
        this.CVV = data().deepCopy(fields()[4].schema(), other.CVV);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'Type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return Type;
    }

    /**
      * Sets the value of the 'Type' field.
      * @param value The value of 'Type'.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Type' field has been set.
      * @return True if the 'Type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Type' field.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder clearType() {
      Type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Number' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumber() {
      return Number;
    }

    /**
      * Sets the value of the 'Number' field.
      * @param value The value of 'Number'.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder setNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Number' field has been set.
      * @return True if the 'Number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Number' field.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder clearNumber() {
      Number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ExpirationMonth' field.
      * @return The value.
      */
    public java.lang.CharSequence getExpirationMonth() {
      return ExpirationMonth;
    }

    /**
      * Sets the value of the 'ExpirationMonth' field.
      * @param value The value of 'ExpirationMonth'.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder setExpirationMonth(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ExpirationMonth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ExpirationMonth' field has been set.
      * @return True if the 'ExpirationMonth' field has been set, false otherwise.
      */
    public boolean hasExpirationMonth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ExpirationMonth' field.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder clearExpirationMonth() {
      ExpirationMonth = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ExpirationYear' field.
      * @return The value.
      */
    public java.lang.CharSequence getExpirationYear() {
      return ExpirationYear;
    }

    /**
      * Sets the value of the 'ExpirationYear' field.
      * @param value The value of 'ExpirationYear'.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder setExpirationYear(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ExpirationYear = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ExpirationYear' field has been set.
      * @return True if the 'ExpirationYear' field has been set, false otherwise.
      */
    public boolean hasExpirationYear() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ExpirationYear' field.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder clearExpirationYear() {
      ExpirationYear = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CVV' field.
      * @return The value.
      */
    public java.lang.CharSequence getCVV() {
      return CVV;
    }

    /**
      * Sets the value of the 'CVV' field.
      * @param value The value of 'CVV'.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder setCVV(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CVV = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CVV' field has been set.
      * @return True if the 'CVV' field has been set, false otherwise.
      */
    public boolean hasCVV() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CVV' field.
      * @return This builder.
      */
    public com.hughes.sdg.avro.types.CreditCardInfo.Builder clearCVV() {
      CVV = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreditCardInfo build() {
      try {
        CreditCardInfo record = new CreditCardInfo();
        record.Type = fieldSetFlags()[0] ? this.Type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Number = fieldSetFlags()[1] ? this.Number : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ExpirationMonth = fieldSetFlags()[2] ? this.ExpirationMonth : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ExpirationYear = fieldSetFlags()[3] ? this.ExpirationYear : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CVV = fieldSetFlags()[4] ? this.CVV : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreditCardInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreditCardInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreditCardInfo>
    READER$ = (org.apache.avro.io.DatumReader<CreditCardInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
