SELECT D2I(SYSDATE) FROM PIN_VIRTUAL_TIME_T;

SELECT SYSDATE FROM PIN_VIRTUAL_TIME_T;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YY';

commit;

SELECT * FROM all_users;

SELECT 
    owner,
    object_name,
    object_type
FROM 
    all_objects
WHERE
    object_name like '%D2I%';
    
CREATE SYNONYM D2I
FOR DATE_TO_INFRANET;

SELECT *
  FROM USER_PROCEDURES
 WHERE object_name = 'CREATE_BRT_WO';

SELECT *
  FROM USER_OBJECTS
 WHERE object_type = 'PROCEDURE'
   AND object_name = 'CREATE_BRT_WO';

VARIABLE RETVAL VARCHAR2(100);

execute CREATE_BRT_WO('DSS200197435', 'A', 'Hazela', 'RarghiArp', '12 Walker Ave', 'Gaithersburg', 'MD', '20877', '3214895630', 'HughesNet Voice Domestic ($29.95)', '.NAD.KE.CONSUMER.DIRECT', :RETVAL);

execute GET_ACCOUNT('Hi', :RETVAL);

print RETVAL;

SELECT COUNT(*) FROM HNS_VOIP_ACTIVATION_STATUS_T WHERE SAN='DSS200197435' AND STATUS IN ('H','D');

SELECT COUNT(*) FROM SERVICE_T S, ACCOUNT_T A WHERE A.ACCOUNT_NO='DSS200197435'
      AND A.POID_ID0=S.ACCOUNT_OBJ_ID0 AND S.POID_TYPE='/service/voip';
      
select * from HNS_VOIP_ACTIVATION_STATUS_T where rownum < 5;
select * from HNS_VOIP_REQUEST_T;


Insert into HNS_VOIP_REQUEST_T 
(WORKORDERNO,CREATED_T,MODIFIED_T,SAN,WORKORDERTYPE,ACCOUNTNAME,FIRSTNAME,LASTNAME,
ADDRESS1,ADDRESS2,CITY,STATE,ZIP,EFFECTIVEDATE,PHONENUMBER,PACKAGE,
ACTIVATIONDATE,TAXEXEMPTIONFLAG,SECURITYLABEL,STATUS,SOURCE,NUM_ATTEMPTS,
BRT_REASON_CODE,FILENAME,MACADDRESS,RATE) 
values 
(98,1370969313,1370971959,'DSS30319556','A','JOHN SALISBURY','FNDSS30319556','LNDSS30319556',
'1234 DSS30 RD',null,'Woodland Park','CO','80863',31,'123-456-7890','Voice Domestic(C)',1370923200,
'N','SECURITY','D','BILLING',1,'0000','HNSVOIPFEED_06112013_1302.csv',null,null);

Insert into HNS_VOIP_ACTIVATION_STATUS_T (SAN,CREATED_T,MODIFIED_T,ACTIVATION_T,STATUS,NUM_ATTEMPTS,ORDER_TYPE) values ('DSS200197435',1372864102,1383298963,0,'H',1,1);

SELECT * FROM HNS_VOIP_REQUEST_T WHERE WORKORDERNO = 20435;

select * from account_t;

commit;

