/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hughes.billing.voipworkorder.dto.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AddVoipWorkOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8577710653954080049L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AddVoipWorkOrder\",\"namespace\":\"com.hughes.billing.voipworkorder.dto.avro\",\"fields\":[{\"name\":\"MessageHeader\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"MessageHeader\",\"fields\":[{\"name\":\"MessageName\",\"type\":[\"null\",\"string\"]},{\"name\":\"Origin\",\"type\":[\"null\",\"string\"]},{\"name\":\"TransactionDateTime\",\"type\":[\"null\",\"string\"]},{\"name\":\"TransactionSequenceId\",\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"MessageData\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"MessageData\",\"fields\":[{\"name\":\"MessageParameters\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"MessageParameter\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"value\",\"type\":[\"null\",\"string\"]}]}]}]},{\"name\":\"Orders\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"Order\",\"fields\":[{\"name\":\"InstallAddress\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"InstallAddress\",\"fields\":[{\"name\":\"Address1\",\"type\":[\"null\",\"string\"]},{\"name\":\"Address2\",\"type\":\"null\"},{\"name\":\"City\",\"type\":[\"null\",\"string\"]},{\"name\":\"Country\",\"type\":[\"null\",\"string\"]},{\"name\":\"State\",\"type\":[\"null\",\"string\"]},{\"name\":\"Zip\",\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"InstallPhone\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"InstallPhone\",\"fields\":[{\"name\":\"Number\",\"type\":[\"null\",\"string\"]},{\"name\":\"Type\",\"type\":[\"null\",\"string\"]}]}]}]},{\"name\":\"OrderInformation\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"OrderInformation\",\"fields\":[{\"name\":\"SAN\",\"type\":[\"null\",\"string\"]}]}]}]}]}]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AddVoipWorkOrder> ENCODER =
      new BinaryMessageEncoder<AddVoipWorkOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AddVoipWorkOrder> DECODER =
      new BinaryMessageDecoder<AddVoipWorkOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AddVoipWorkOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AddVoipWorkOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AddVoipWorkOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AddVoipWorkOrder>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AddVoipWorkOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AddVoipWorkOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AddVoipWorkOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AddVoipWorkOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.hughes.billing.voipworkorder.dto.avro.MessageHeader MessageHeader;
   private com.hughes.billing.voipworkorder.dto.avro.MessageData MessageData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AddVoipWorkOrder() {}

  /**
   * All-args constructor.
   * @param MessageHeader The new value for MessageHeader
   * @param MessageData The new value for MessageData
   */
  public AddVoipWorkOrder(com.hughes.billing.voipworkorder.dto.avro.MessageHeader MessageHeader, com.hughes.billing.voipworkorder.dto.avro.MessageData MessageData) {
    this.MessageHeader = MessageHeader;
    this.MessageData = MessageData;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MessageHeader;
    case 1: return MessageData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MessageHeader = (com.hughes.billing.voipworkorder.dto.avro.MessageHeader)value$; break;
    case 1: MessageData = (com.hughes.billing.voipworkorder.dto.avro.MessageData)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'MessageHeader' field.
   * @return The value of the 'MessageHeader' field.
   */
  public com.hughes.billing.voipworkorder.dto.avro.MessageHeader getMessageHeader() {
    return MessageHeader;
  }


  /**
   * Sets the value of the 'MessageHeader' field.
   * @param value the value to set.
   */
  public void setMessageHeader(com.hughes.billing.voipworkorder.dto.avro.MessageHeader value) {
    this.MessageHeader = value;
  }

  /**
   * Gets the value of the 'MessageData' field.
   * @return The value of the 'MessageData' field.
   */
  public com.hughes.billing.voipworkorder.dto.avro.MessageData getMessageData() {
    return MessageData;
  }


  /**
   * Sets the value of the 'MessageData' field.
   * @param value the value to set.
   */
  public void setMessageData(com.hughes.billing.voipworkorder.dto.avro.MessageData value) {
    this.MessageData = value;
  }

  /**
   * Creates a new AddVoipWorkOrder RecordBuilder.
   * @return A new AddVoipWorkOrder RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder newBuilder() {
    return new com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder();
  }

  /**
   * Creates a new AddVoipWorkOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AddVoipWorkOrder RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder other) {
    if (other == null) {
      return new com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder();
    } else {
      return new com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder(other);
    }
  }

  /**
   * Creates a new AddVoipWorkOrder RecordBuilder by copying an existing AddVoipWorkOrder instance.
   * @param other The existing instance to copy.
   * @return A new AddVoipWorkOrder RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder other) {
    if (other == null) {
      return new com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder();
    } else {
      return new com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for AddVoipWorkOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AddVoipWorkOrder>
    implements org.apache.avro.data.RecordBuilder<AddVoipWorkOrder> {

    private com.hughes.billing.voipworkorder.dto.avro.MessageHeader MessageHeader;
    private com.hughes.billing.voipworkorder.dto.avro.MessageHeader.Builder MessageHeaderBuilder;
    private com.hughes.billing.voipworkorder.dto.avro.MessageData MessageData;
    private com.hughes.billing.voipworkorder.dto.avro.MessageData.Builder MessageDataBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MessageHeader)) {
        this.MessageHeader = data().deepCopy(fields()[0].schema(), other.MessageHeader);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMessageHeaderBuilder()) {
        this.MessageHeaderBuilder = com.hughes.billing.voipworkorder.dto.avro.MessageHeader.newBuilder(other.getMessageHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.MessageData)) {
        this.MessageData = data().deepCopy(fields()[1].schema(), other.MessageData);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasMessageDataBuilder()) {
        this.MessageDataBuilder = com.hughes.billing.voipworkorder.dto.avro.MessageData.newBuilder(other.getMessageDataBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AddVoipWorkOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.MessageHeader)) {
        this.MessageHeader = data().deepCopy(fields()[0].schema(), other.MessageHeader);
        fieldSetFlags()[0] = true;
      }
      this.MessageHeaderBuilder = null;
      if (isValidValue(fields()[1], other.MessageData)) {
        this.MessageData = data().deepCopy(fields()[1].schema(), other.MessageData);
        fieldSetFlags()[1] = true;
      }
      this.MessageDataBuilder = null;
    }

    /**
      * Gets the value of the 'MessageHeader' field.
      * @return The value.
      */
    public com.hughes.billing.voipworkorder.dto.avro.MessageHeader getMessageHeader() {
      return MessageHeader;
    }


    /**
      * Sets the value of the 'MessageHeader' field.
      * @param value The value of 'MessageHeader'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder setMessageHeader(com.hughes.billing.voipworkorder.dto.avro.MessageHeader value) {
      validate(fields()[0], value);
      this.MessageHeaderBuilder = null;
      this.MessageHeader = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageHeader' field has been set.
      * @return True if the 'MessageHeader' field has been set, false otherwise.
      */
    public boolean hasMessageHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'MessageHeader' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.hughes.billing.voipworkorder.dto.avro.MessageHeader.Builder getMessageHeaderBuilder() {
      if (MessageHeaderBuilder == null) {
        if (hasMessageHeader()) {
          setMessageHeaderBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageHeader.newBuilder(MessageHeader));
        } else {
          setMessageHeaderBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageHeader.newBuilder());
        }
      }
      return MessageHeaderBuilder;
    }

    /**
     * Sets the Builder instance for the 'MessageHeader' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder setMessageHeaderBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageHeader.Builder value) {
      clearMessageHeader();
      MessageHeaderBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'MessageHeader' field has an active Builder instance
     * @return True if the 'MessageHeader' field has an active Builder instance
     */
    public boolean hasMessageHeaderBuilder() {
      return MessageHeaderBuilder != null;
    }

    /**
      * Clears the value of the 'MessageHeader' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder clearMessageHeader() {
      MessageHeader = null;
      MessageHeaderBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'MessageData' field.
      * @return The value.
      */
    public com.hughes.billing.voipworkorder.dto.avro.MessageData getMessageData() {
      return MessageData;
    }


    /**
      * Sets the value of the 'MessageData' field.
      * @param value The value of 'MessageData'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder setMessageData(com.hughes.billing.voipworkorder.dto.avro.MessageData value) {
      validate(fields()[1], value);
      this.MessageDataBuilder = null;
      this.MessageData = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageData' field has been set.
      * @return True if the 'MessageData' field has been set, false otherwise.
      */
    public boolean hasMessageData() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'MessageData' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.hughes.billing.voipworkorder.dto.avro.MessageData.Builder getMessageDataBuilder() {
      if (MessageDataBuilder == null) {
        if (hasMessageData()) {
          setMessageDataBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageData.newBuilder(MessageData));
        } else {
          setMessageDataBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageData.newBuilder());
        }
      }
      return MessageDataBuilder;
    }

    /**
     * Sets the Builder instance for the 'MessageData' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder setMessageDataBuilder(com.hughes.billing.voipworkorder.dto.avro.MessageData.Builder value) {
      clearMessageData();
      MessageDataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'MessageData' field has an active Builder instance
     * @return True if the 'MessageData' field has an active Builder instance
     */
    public boolean hasMessageDataBuilder() {
      return MessageDataBuilder != null;
    }

    /**
      * Clears the value of the 'MessageData' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.AddVoipWorkOrder.Builder clearMessageData() {
      MessageData = null;
      MessageDataBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AddVoipWorkOrder build() {
      try {
        AddVoipWorkOrder record = new AddVoipWorkOrder();
        if (MessageHeaderBuilder != null) {
          try {
            record.MessageHeader = this.MessageHeaderBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("MessageHeader"));
            throw e;
          }
        } else {
          record.MessageHeader = fieldSetFlags()[0] ? this.MessageHeader : (com.hughes.billing.voipworkorder.dto.avro.MessageHeader) defaultValue(fields()[0]);
        }
        if (MessageDataBuilder != null) {
          try {
            record.MessageData = this.MessageDataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("MessageData"));
            throw e;
          }
        } else {
          record.MessageData = fieldSetFlags()[1] ? this.MessageData : (com.hughes.billing.voipworkorder.dto.avro.MessageData) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AddVoipWorkOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<AddVoipWorkOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AddVoipWorkOrder>
    READER$ = (org.apache.avro.io.DatumReader<AddVoipWorkOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.MessageHeader == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.MessageHeader.customEncode(out);
    }

    if (this.MessageData == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.MessageData.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.MessageHeader = null;
      } else {
        if (this.MessageHeader == null) {
          this.MessageHeader = new com.hughes.billing.voipworkorder.dto.avro.MessageHeader();
        }
        this.MessageHeader.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.MessageData = null;
      } else {
        if (this.MessageData == null) {
          this.MessageData = new com.hughes.billing.voipworkorder.dto.avro.MessageData();
        }
        this.MessageData.customDecode(in);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.MessageHeader = null;
          } else {
            if (this.MessageHeader == null) {
              this.MessageHeader = new com.hughes.billing.voipworkorder.dto.avro.MessageHeader();
            }
            this.MessageHeader.customDecode(in);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.MessageData = null;
          } else {
            if (this.MessageData == null) {
              this.MessageData = new com.hughes.billing.voipworkorder.dto.avro.MessageData();
            }
            this.MessageData.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










