/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hughes.billing.voipworkorder.dto.avro.ack;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8264193980634448852L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageHeader\",\"namespace\":\"com.hughes.billing.voipworkorder.dto.avro.ack\",\"fields\":[{\"name\":\"TransactionSequenceId\",\"type\":\"string\"},{\"name\":\"TransactionDateTime\",\"type\":\"string\"},{\"name\":\"MessageName\",\"type\":\"string\"},{\"name\":\"Origin\",\"type\":\"string\"},{\"name\":\"CorrelationId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageHeader> ENCODER =
      new BinaryMessageEncoder<MessageHeader>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageHeader> DECODER =
      new BinaryMessageDecoder<MessageHeader>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MessageHeader> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MessageHeader> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageHeader>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MessageHeader to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MessageHeader from a ByteBuffer. */
  public static MessageHeader fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence TransactionSequenceId;
  @Deprecated public java.lang.CharSequence TransactionDateTime;
  @Deprecated public java.lang.CharSequence MessageName;
  @Deprecated public java.lang.CharSequence Origin;
  @Deprecated public java.lang.CharSequence CorrelationId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageHeader() {}

  /**
   * All-args constructor.
   * @param TransactionSequenceId The new value for TransactionSequenceId
   * @param TransactionDateTime The new value for TransactionDateTime
   * @param MessageName The new value for MessageName
   * @param Origin The new value for Origin
   * @param CorrelationId The new value for CorrelationId
   */
  public MessageHeader(java.lang.CharSequence TransactionSequenceId, java.lang.CharSequence TransactionDateTime, java.lang.CharSequence MessageName, java.lang.CharSequence Origin, java.lang.CharSequence CorrelationId) {
    this.TransactionSequenceId = TransactionSequenceId;
    this.TransactionDateTime = TransactionDateTime;
    this.MessageName = MessageName;
    this.Origin = Origin;
    this.CorrelationId = CorrelationId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return TransactionSequenceId;
    case 1: return TransactionDateTime;
    case 2: return MessageName;
    case 3: return Origin;
    case 4: return CorrelationId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: TransactionSequenceId = (java.lang.CharSequence)value$; break;
    case 1: TransactionDateTime = (java.lang.CharSequence)value$; break;
    case 2: MessageName = (java.lang.CharSequence)value$; break;
    case 3: Origin = (java.lang.CharSequence)value$; break;
    case 4: CorrelationId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'TransactionSequenceId' field.
   * @return The value of the 'TransactionSequenceId' field.
   */
  public java.lang.CharSequence getTransactionSequenceId() {
    return TransactionSequenceId;
  }

  /**
   * Sets the value of the 'TransactionSequenceId' field.
   * @param value the value to set.
   */
  public void setTransactionSequenceId(java.lang.CharSequence value) {
    this.TransactionSequenceId = value;
  }

  /**
   * Gets the value of the 'TransactionDateTime' field.
   * @return The value of the 'TransactionDateTime' field.
   */
  public java.lang.CharSequence getTransactionDateTime() {
    return TransactionDateTime;
  }

  /**
   * Sets the value of the 'TransactionDateTime' field.
   * @param value the value to set.
   */
  public void setTransactionDateTime(java.lang.CharSequence value) {
    this.TransactionDateTime = value;
  }

  /**
   * Gets the value of the 'MessageName' field.
   * @return The value of the 'MessageName' field.
   */
  public java.lang.CharSequence getMessageName() {
    return MessageName;
  }

  /**
   * Sets the value of the 'MessageName' field.
   * @param value the value to set.
   */
  public void setMessageName(java.lang.CharSequence value) {
    this.MessageName = value;
  }

  /**
   * Gets the value of the 'Origin' field.
   * @return The value of the 'Origin' field.
   */
  public java.lang.CharSequence getOrigin() {
    return Origin;
  }

  /**
   * Sets the value of the 'Origin' field.
   * @param value the value to set.
   */
  public void setOrigin(java.lang.CharSequence value) {
    this.Origin = value;
  }

  /**
   * Gets the value of the 'CorrelationId' field.
   * @return The value of the 'CorrelationId' field.
   */
  public java.lang.CharSequence getCorrelationId() {
    return CorrelationId;
  }

  /**
   * Sets the value of the 'CorrelationId' field.
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.CharSequence value) {
    this.CorrelationId = value;
  }

  /**
   * Creates a new MessageHeader RecordBuilder.
   * @return A new MessageHeader RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder newBuilder() {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder();
  }

  /**
   * Creates a new MessageHeader RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageHeader RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder other) {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder(other);
  }

  /**
   * Creates a new MessageHeader RecordBuilder by copying an existing MessageHeader instance.
   * @param other The existing instance to copy.
   * @return A new MessageHeader RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader other) {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder(other);
  }

  /**
   * RecordBuilder for MessageHeader instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageHeader>
    implements org.apache.avro.data.RecordBuilder<MessageHeader> {

    private java.lang.CharSequence TransactionSequenceId;
    private java.lang.CharSequence TransactionDateTime;
    private java.lang.CharSequence MessageName;
    private java.lang.CharSequence Origin;
    private java.lang.CharSequence CorrelationId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.TransactionSequenceId)) {
        this.TransactionSequenceId = data().deepCopy(fields()[0].schema(), other.TransactionSequenceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TransactionDateTime)) {
        this.TransactionDateTime = data().deepCopy(fields()[1].schema(), other.TransactionDateTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MessageName)) {
        this.MessageName = data().deepCopy(fields()[2].schema(), other.MessageName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Origin)) {
        this.Origin = data().deepCopy(fields()[3].schema(), other.Origin);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CorrelationId)) {
        this.CorrelationId = data().deepCopy(fields()[4].schema(), other.CorrelationId);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MessageHeader instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.TransactionSequenceId)) {
        this.TransactionSequenceId = data().deepCopy(fields()[0].schema(), other.TransactionSequenceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TransactionDateTime)) {
        this.TransactionDateTime = data().deepCopy(fields()[1].schema(), other.TransactionDateTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MessageName)) {
        this.MessageName = data().deepCopy(fields()[2].schema(), other.MessageName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Origin)) {
        this.Origin = data().deepCopy(fields()[3].schema(), other.Origin);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CorrelationId)) {
        this.CorrelationId = data().deepCopy(fields()[4].schema(), other.CorrelationId);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'TransactionSequenceId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionSequenceId() {
      return TransactionSequenceId;
    }

    /**
      * Sets the value of the 'TransactionSequenceId' field.
      * @param value The value of 'TransactionSequenceId'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder setTransactionSequenceId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.TransactionSequenceId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'TransactionSequenceId' field has been set.
      * @return True if the 'TransactionSequenceId' field has been set, false otherwise.
      */
    public boolean hasTransactionSequenceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'TransactionSequenceId' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder clearTransactionSequenceId() {
      TransactionSequenceId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TransactionDateTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionDateTime() {
      return TransactionDateTime;
    }

    /**
      * Sets the value of the 'TransactionDateTime' field.
      * @param value The value of 'TransactionDateTime'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder setTransactionDateTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.TransactionDateTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TransactionDateTime' field has been set.
      * @return True if the 'TransactionDateTime' field has been set, false otherwise.
      */
    public boolean hasTransactionDateTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TransactionDateTime' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder clearTransactionDateTime() {
      TransactionDateTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'MessageName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageName() {
      return MessageName;
    }

    /**
      * Sets the value of the 'MessageName' field.
      * @param value The value of 'MessageName'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder setMessageName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.MessageName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageName' field has been set.
      * @return True if the 'MessageName' field has been set, false otherwise.
      */
    public boolean hasMessageName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'MessageName' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder clearMessageName() {
      MessageName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Origin' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrigin() {
      return Origin;
    }

    /**
      * Sets the value of the 'Origin' field.
      * @param value The value of 'Origin'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder setOrigin(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Origin = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Origin' field has been set.
      * @return True if the 'Origin' field has been set, false otherwise.
      */
    public boolean hasOrigin() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Origin' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder clearOrigin() {
      Origin = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CorrelationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCorrelationId() {
      return CorrelationId;
    }

    /**
      * Sets the value of the 'CorrelationId' field.
      * @param value The value of 'CorrelationId'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder setCorrelationId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CorrelationId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CorrelationId' field has been set.
      * @return True if the 'CorrelationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CorrelationId' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.MessageHeader.Builder clearCorrelationId() {
      CorrelationId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageHeader build() {
      try {
        MessageHeader record = new MessageHeader();
        record.TransactionSequenceId = fieldSetFlags()[0] ? this.TransactionSequenceId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.TransactionDateTime = fieldSetFlags()[1] ? this.TransactionDateTime : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.MessageName = fieldSetFlags()[2] ? this.MessageName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Origin = fieldSetFlags()[3] ? this.Origin : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CorrelationId = fieldSetFlags()[4] ? this.CorrelationId : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageHeader>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageHeader>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageHeader>
    READER$ = (org.apache.avro.io.DatumReader<MessageHeader>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
