/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hughes.billing.voipworkorder.dto.avro.ack;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderInformation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7347465559494814644L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderInformation\",\"namespace\":\"com.hughes.billing.voipworkorder.dto.avro.ack\",\"fields\":[{\"name\":\"SAN\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderInformation> ENCODER =
      new BinaryMessageEncoder<OrderInformation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderInformation> DECODER =
      new BinaryMessageDecoder<OrderInformation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderInformation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderInformation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderInformation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderInformation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderInformation from a ByteBuffer. */
  public static OrderInformation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence SAN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderInformation() {}

  /**
   * All-args constructor.
   * @param SAN The new value for SAN
   */
  public OrderInformation(java.lang.CharSequence SAN) {
    this.SAN = SAN;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SAN;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SAN = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'SAN' field.
   * @return The value of the 'SAN' field.
   */
  public java.lang.CharSequence getSAN() {
    return SAN;
  }

  /**
   * Sets the value of the 'SAN' field.
   * @param value the value to set.
   */
  public void setSAN(java.lang.CharSequence value) {
    this.SAN = value;
  }

  /**
   * Creates a new OrderInformation RecordBuilder.
   * @return A new OrderInformation RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder newBuilder() {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder();
  }

  /**
   * Creates a new OrderInformation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderInformation RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder other) {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder(other);
  }

  /**
   * Creates a new OrderInformation RecordBuilder by copying an existing OrderInformation instance.
   * @param other The existing instance to copy.
   * @return A new OrderInformation RecordBuilder
   */
  public static com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder newBuilder(com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation other) {
    return new com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder(other);
  }

  /**
   * RecordBuilder for OrderInformation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderInformation>
    implements org.apache.avro.data.RecordBuilder<OrderInformation> {

    private java.lang.CharSequence SAN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SAN)) {
        this.SAN = data().deepCopy(fields()[0].schema(), other.SAN);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderInformation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.SAN)) {
        this.SAN = data().deepCopy(fields()[0].schema(), other.SAN);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'SAN' field.
      * @return The value.
      */
    public java.lang.CharSequence getSAN() {
      return SAN;
    }

    /**
      * Sets the value of the 'SAN' field.
      * @param value The value of 'SAN'.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder setSAN(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.SAN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'SAN' field has been set.
      * @return True if the 'SAN' field has been set, false otherwise.
      */
    public boolean hasSAN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'SAN' field.
      * @return This builder.
      */
    public com.hughes.billing.voipworkorder.dto.avro.ack.OrderInformation.Builder clearSAN() {
      SAN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderInformation build() {
      try {
        OrderInformation record = new OrderInformation();
        record.SAN = fieldSetFlags()[0] ? this.SAN : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderInformation>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderInformation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderInformation>
    READER$ = (org.apache.avro.io.DatumReader<OrderInformation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
